### ISSUE TITLE
레포 member 추가

### ISSUE THREAD

**Issue by lukasjhan** [tree-s-computer/-IT-#1]
@yunseorim1116 제가 이 레포에 권한이 없더라구여.

제가 @tree-s-computer/tree 팀을 하나 만들었어요. 레포에 팀을 추가해주시거나 저를 추가해주세요.
혹시 제가 어제 만든 레포에는 쓰기 권한이 있으신가요?

**Comment by yunseorim1116** [comment]
![image](https://github.com/tree-s-computer/-IT-/assets/94429667/f2acd4d1-318f-4eb2-b2ad-9bf49977defe)
레포 추가했습니다! 
jwt 레파지토리에 추가 커밋 남겼습니다. 쓰기 권한 있는 것 같아요 !
질문 폴더를 따로 만들었는데 폴더를 삭제하고 ISSUE 로 옮겨가는게 나을까요~?!

**Comment by lukasjhan** [comment]
이슈가 멘션이 되어서 그게 더 편할것 같아요 :) 
아마 org에 권한체계가 있나봐요. admin은 모든 레포의 쓰기권한을 갖는다던지, 그건 월요일에 잠깐 같이 봐요. 👍🏻
