### ISSUE TITLE
Stack managing

### ISSUE THREAD

**Issue by lukasjhan** [tree-s-computer/-IT-#5]
블로글 쓰신거 봤어요 :slightly_smiling_face: 잘쓰셨더라구요.
프로그램에서 스택관리하는 부분을 더 궁금해하시는거 같아서 도움이 될까 관련된 사진을 올려드려요.

![image](https://github.com/tree-s-computer/-IT-/assets/86042901/df49959c-db7b-4fd6-979b-93c72cc9fd12)

**Comment by lukasjhan** [comment]
@yunseorim1116

**Comment by yunseorim1116** [comment]
- 함수를 실행하면 스택 프레임이 쌓인다. 
- 그 스택 프레임 끝에 함수가 리턴 될때 함수가 어디로 가야하는지 쓰여있다. 

- 컴파일러가 스택을 없앤다. (정확히는 지워지는 것이 아니다. 덮어 씌우는 것이다.(?) )
- 함수 콜을 하면 컴파일러가 함수 콜을 위한 기계어를 만든다. 

요 설명을 듣고 그림을 보니 더 잘 이해가 가는 것 같아요! 감사합니다 :D

**Comment by lukasjhan** [comment]
https://youtu.be/N3o5yHYLviQ

@yunseorim1116 제가 좋은영상을 하나 더 찾았습니다. 다 영어긴한데 제가 번역을 좀 해드릴까여?
